language: node_js
node_js:
  # - "12" Doesn't work yet - requires Jasmine updates/replacement
  # - "10" Doesn't work yet - requires Jasmine updates/replacement
  - "12"
  - "11"
  - "10"
  - "8"
  - "6"
  - "4"
  - "0.12"
  - "0.10"
script: "npm run-script ci"
